class AiAssistantController < ApplicationController
  layout "dashboard"

  def index
  end

  def generate
    @prompt =
      params[:prompt]

    @generation_type =
      params[:generation_type]

    @result =
      Ai::Assistant.generate(
        @prompt,
        @generation_type
      )

    session[:generated_result] =
      @result

    session[:generation_type] =
      @generation_type

    respond_to do |format|
      format.turbo_stream
      format.html { render :index }
    end
  end

  def save_story
    result =
      session[:generated_result]

    epic =
      Epic.find(
        params[:epic_id]
      )

    title =
      result
        .match(/## Title\s*(.*?)\s*## User Story/m)
        &.captures
        &.first
        &.strip

    user_story =
      result
        .match(/## User Story\s*(.*?)\s*## Acceptance Criteria/m)
        &.captures
        &.first
        &.strip

    story_points =
      result
        .match(/## Story Points\s*(\d+)/)
        &.captures
        &.first

    Story.create!(
      title: title.presence || "AI Generated Story",
      description: user_story.presence || result,
      story_points: story_points || 5,
      epic: epic,
      status: :todo
    )

    clear_ai_session

    redirect_to stories_path,
                notice: "Story created successfully."

  rescue StandardError => e

    redirect_to ai_assistant_index_path,
                alert: e.message
  end

  def save_tasks
    result =
      session[:generated_result]

    story =
      Story.find(
        params[:story_id]
      )

    result.each_line do |line|
      line =
        line.strip

      next unless line.start_with?("-")

      Task.create!(
        title: line.delete_prefix("-").strip,
        description: "Generated by SprintPilot AI",
        story: story,
        status: :todo
      )
    end

    clear_ai_session

    redirect_to tasks_path,
                notice: "Tasks created successfully."

  rescue StandardError => e

    redirect_to ai_assistant_index_path,
                alert: e.message
  end

  def save_epic
    result =
      session[:generated_result]

    project =
      Project.find(
        params[:project_id]
      )

    Epic.create!(
      title: params[:title].presence || "AI Generated Epic",
      description: result,
      project: project
    )

    clear_ai_session

    redirect_to epics_path,
                notice: "Epic created successfully."

  rescue StandardError => e

    redirect_to ai_assistant_index_path,
                alert: e.message
  end

  def save_sprint
    result =
      session[:generated_result]

    project =
      Project.find(
        params[:project_id]
      )

    Sprint.create!(
      name: params[:name].presence || "AI Generated Sprint",
      goal: result,
      project: project,
      status: :planned,
      start_date: Date.today,
      end_date: Date.today + 14.days
    )

    clear_ai_session

    redirect_to sprints_path,
                notice: "Sprint created successfully."

  rescue StandardError => e

    redirect_to ai_assistant_index_path,
                alert: e.message
  end

  private

  def clear_ai_session
    session.delete(
      :generated_result
    )

    session.delete(
      :generation_type
    )
  end
end
