class AiTasksController < ApplicationController
  layout "dashboard"

  def index
    @stories =
      Story.includes(:epic)
           .order(:title)
  end

  def generate
    @story =
      Story.find(
        params[:story_id]
      )

    @result =
      Ai::TaskGenerator.generate(
        @story.description
      )

    session[:generated_tasks] =
      @result

    session[:story_id] =
      @story.id

    respond_to do |format|
      format.turbo_stream
      format.html { render :index }
    end
  end

  def save_tasks
    generated_tasks =
      session[:generated_tasks]

    story_id =
      session[:story_id]

    unless generated_tasks.present?

      redirect_to ai_tasks_path,
                  alert: "Generate tasks first."

      return

    end

    generated_tasks.each_line do |line|
      line = line.strip

      next unless line.start_with?("-")

      Task.create!(
        title: line.delete_prefix("-").strip,
        description: "Generated by SprintPilot AI",
        status: :todo,
        story_id: story_id
      )
    end

    session.delete(:generated_tasks)
    session.delete(:story_id)

    redirect_to tasks_path,
                notice: "Tasks created successfully."
  end
end
